Set-Content -Path .github\workflows\code-quality.yml -Value @'
name: FIG Code Quality

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'
  schedule:
    - cron: '0 0 * * 1' # Run weekly on Mondays at midnight

jobs:
  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper analysis
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint with detailed report
        run: npx eslint --ext .js,.jsx,.ts,.tsx src/ --format html --output-file eslint-report.html
        continue-on-error: true
      
      - name: Run Type checking
        run: npx tsc --noEmit
        continue-on-error: true
      
      - name: Check for unused dependencies
        run: npx depcheck --json > depcheck-report.json
        continue-on-error: true
        
      - name: Check for vulnerabilities
        run: npm audit --json > npm-audit-report.json
        continue-on-error: true
        
      - name: Analyze bundle size
        run: |
          npm run build
          npx source-map-explorer 'dist/assets/*.js' --json > bundle-analysis.json
        continue-on-error: true
        
      - name: Upload analysis reports
        uses: actions/upload-artifact@v3
        with:
          name: code-quality-reports
          path: |
            eslint-report.html
            depcheck-report.json
            npm-audit-report.json
            bundle-analysis.json
          retention-days: 14
'@