Set-Content -Path .github\workflows\scheduled-tasks.yml -Value @'
name: FIG Scheduled Tasks

on:
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2 AM UTC
  workflow_dispatch:
    inputs:
      task:
        description: 'Task to run manually'
        required: true
        default: 'backup'
        type: choice
        options:
        - backup
        - clean-stale-data
        - generate-reports

jobs:
  database-backup:
    name: Firestore Database Backup
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event.inputs.task == 'backup'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
        
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
          
      - name: Export Firestore to Storage Bucket
        run: |
          TODAY=$(date +"%Y-%m-%d")
          gcloud firestore export gs://${{ secrets.BACKUP_BUCKET }}/backups/${TODAY}
'@